version: '3.8'  
services:  
  postgres:  
    image: postgres:13  
    environment:  
      POSTGRES_USER: nestuser  
      POSTGRES_PASSWORD: nestpassword  
      POSTGRES_DB: github_users  
    ports:  
      - "5434:5434"  
    volumes:  
      - postgres_data:/var/lib/postgresql/data  
volumes:  
  postgres_data:  
