version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: github_users_db 
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: github_users
    ports:
      - "5434:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestuser -d github_users"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
